<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CraftToolSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $rows = [
            [
                "item_name" => "プラチナの鍛冶ハンマー",
                "craft_level" => 28,
                "recipe_book" => "1139",
                "recipe_place" => "メギストリスレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具ハンマー",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "プラチナの職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 5],
                    ["item_id" => 599, "qty" => 4],
                    ["item_id" => 879, "qty" => 1],
                    ["item_id" => 865, "qty" => 4],
                ],
                "slot_grid_json" => [
                    ["95～103", "120～126"],
                    ["75～85", "90～98"],
                    ["60～73", "-"],
                ],
            ],
            [
                "item_name" => "プラチナの木工刀",
                "craft_level" => 26,
                "recipe_book" => "1140",
                "recipe_place" => "メギストリスレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具木工刀",
                "slot_grid_cols" => 1,
                "group_kind" => "craft_tool_set",
                "group_name" => "プラチナの職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 5],
                    ["item_id" => 561, "qty" => 4],
                    ["item_id" => 638, "qty" => 1],
                    ["item_id" => 865, "qty" => 4],
                ],
                "slot_grid_json" => [
                    ["170～175"],
                    ["135～143"],
                    ["115～122"],
                ],
            ],
            [
                "item_name" => "プラチナのさいほう針",
                "craft_level" => 25,
                "recipe_book" => "1141",
                "recipe_place" => "メギストリスレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具さいほう針",
                "slot_grid_cols" => 1,
                "group_kind" => "craft_tool_set",
                "group_name" => "プラチナの職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 5],
                    ["item_id" => 555, "qty" => 4],
                    ["item_id" => 810, "qty" => 1],
                    ["item_id" => 865, "qty" => 4],
                ],
                "slot_grid_json" => [
                    ["180～186"],
                    ["240～244"],
                ],
            ],
            [
                "item_name" => "プラチナのフライパン",
                "craft_level" => 28,
                "recipe_book" => "1144",
                "recipe_place" => "メギストリスレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具フライパン",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "プラチナの職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 5],
                    ["item_id" => 884, "qty" => 4],
                    ["item_id" => 697, "qty" => 1],
                    ["item_id" => 865, "qty" => 4],
                ],
                "slot_grid_json" => [
                    ["55～66", "42～50"],
                    ["55～66", "78～87"],
                    ["90～98", "78～87"],
                    ["42～50", "-"],
                ],
            ],
            [
                "item_name" => "プラチナの錬金ランプ",
                "craft_level" => 27,
                "recipe_book" => "1142",
                "recipe_place" => "メギストリスレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具錬金ランプ",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "プラチナの職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 5],
                    ["item_id" => 815, "qty" => 4],
                    ["item_id" => 781, "qty" => 1],
                    ["item_id" => 865, "qty" => 4],
                ],
                "slot_grid_json" => [
                    ["115～123", "100～107"],
                    ["145～155", "80～90"],
                ],
            ],
            [
                "item_name" => "プラチナの錬金ツボ",
                "craft_level" => 30,
                "recipe_book" => "1143",
                "recipe_place" => "メギストリスレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具錬金ツボ",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "プラチナの職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 5],
                    ["item_id" => 755, "qty" => 4],
                    ["item_id" => 551, "qty" => 1],
                    ["item_id" => 865, "qty" => 4],
                ],
                "slot_grid_json" => [
                    ["60～70", "90～100"],
                    ["70～77", "70～77"],
                    ["90～100", "60～70"],
                ],
            ],

            [
                "item_name" => "超鍛冶ハンマー",
                "craft_level" => 32,
                "recipe_book" => "1145",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具ハンマー",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "超の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 16],
                    ["item_id" => 754, "qty" => 8],
                    ["item_id" => 545, "qty" => 8],
                    ["item_id" => 865, "qty" => 8],
                ],
                "slot_grid_json" => [
                    ["130～140", "105～111"],
                    ["105～113", "130～140"],
                    ["90～96", "-"],
                ],
            ],
            [
                "item_name" => "超木工刀",
                "craft_level" => 31,
                "recipe_book" => "1146",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具木工刀",
                "slot_grid_cols" => 1,
                "group_kind" => "craft_tool_set",
                "group_name" => "超の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 16],
                    ["item_id" => 760, "qty" => 40],
                    ["item_id" => 545, "qty" => 8],
                    ["item_id" => 865, "qty" => 8],
                ],
                "slot_grid_json" => [
                    ["180～186"],
                    ["140～144"],
                    ["240～256"],
                ],
            ],
            [
                "item_name" => "超さいほう針",
                "craft_level" => 30,
                "recipe_book" => "1147",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具さいほう針",
                "slot_grid_cols" => 1,
                "group_kind" => "craft_tool_set",
                "group_name" => "超の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 16],
                    ["item_id" => 535, "qty" => 40],
                    ["item_id" => 545, "qty" => 8],
                    ["item_id" => 865, "qty" => 8],
                ],
                "slot_grid_json" => [
                    ["310～316"],
                    ["250～254"],
                ],
            ],
            [
                "item_name" => "超フライパン",
                "craft_level" => 32,
                "recipe_book" => "1150",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具フライパン",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "超の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 16],
                    ["item_id" => 728, "qty" => 40],
                    ["item_id" => 545, "qty" => 8],
                    ["item_id" => 865, "qty" => 8],
                ],
                "slot_grid_json" => [
                    ["65～76", "65～76"],
                    ["65～76", "80～88"],
                    ["109～115", "96～105"],
                    ["80～88", "-"],
                ],
            ],
            [
                "item_name" => "超錬金ランプ",
                "craft_level" => 32,
                "recipe_book" => "1148",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具錬金ランプ",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "超の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 16],
                    ["item_id" => 818, "qty" => 40],
                    ["item_id" => 545, "qty" => 8],
                    ["item_id" => 865, "qty" => 8],
                ],
                "slot_grid_json" => [
                    ["100～106", "165～175"],
                    ["165～173", "130～140"],
                ],
            ],
            [
                "item_name" => "超錬金ツボ",
                "craft_level" => 33,
                "recipe_book" => "1149",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具錬金ツボ",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "超の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 16],
                    ["item_id" => 867, "qty" => 40],
                    ["item_id" => 545, "qty" => 8],
                    ["item_id" => 865, "qty" => 8],
                ],
                "slot_grid_json" => [
                    ["90～98", "90～98"],
                    ["114～124", "114～124"],
                    ["76～82", "76～82"],
                ],
            ],

            [
                "item_name" => "奇跡の鍛冶ハンマー",
                "craft_level" => 34,
                "recipe_book" => "1151",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具ハンマー",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "奇跡の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 24],
                    ["item_id" => 596, "qty" => 64],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 12],
                ],
                "slot_grid_json" => [
                    ["150～156", "160～170"],
                    ["80～86", "130～139"],
                    ["120～129", "-"],
                ],
            ],
            [
                "item_name" => "奇跡の木工刀",
                "craft_level" => 34,
                "recipe_book" => "1152",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具木工刀",
                "slot_grid_cols" => 1,
                "group_kind" => "craft_tool_set",
                "group_name" => "奇跡の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 24],
                    ["item_id" => 597, "qty" => 64],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 12],
                ],
                "slot_grid_json" => [
                    ["230～238"],
                    ["200～206"],
                    ["274～286"],
                ],
            ],
            [
                "item_name" => "奇跡のさいほう針",
                "craft_level" => 34,
                "recipe_book" => "1153",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具さいほう針",
                "slot_grid_cols" => 1,
                "group_kind" => "craft_tool_set",
                "group_name" => "奇跡の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 24],
                    ["item_id" => 653, "qty" => 64],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 12],
                ],
                "slot_grid_json" => [
                    ["314～320"],
                    ["390～404"],
                ],
            ],
            [
                "item_name" => "奇跡のフライパン",
                "craft_level" => 34,
                "recipe_book" => "1156",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具フライパン",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "奇跡の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 24],
                    ["item_id" => 845, "qty" => 64],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 12],
                ],
                "slot_grid_json" => [
                    ["72～82", "110～120"],
                    ["134～146", "90～96"],
                    ["90～96", "72～82"],
                    ["72～82", "-"],
                ],
            ],
            [
                "item_name" => "奇跡の錬金ランプ",
                "craft_level" => 34,
                "recipe_book" => "1154",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具錬金ランプ",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "奇跡の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 24],
                    ["item_id" => 617, "qty" => 64],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 12],
                ],
                "slot_grid_json" => [
                    ["120～132", "190～198"],
                    ["190～198", "140～146"],
                ],
            ],
            [
                "item_name" => "奇跡の錬金ツボ",
                "craft_level" => 34,
                "recipe_book" => "1155",
                "recipe_place" => "ギルド素材屋",
                "slot" => "その他",
                "slot_grid_type" => "道具錬金ツボ",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "奇跡の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 816, "qty" => 24],
                    ["item_id" => 845, "qty" => 64],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 12],
                ],
                "slot_grid_json" => [
                    ["70～80", "150～158"],
                    ["150～158", "100～106"],
                    ["100～106", "70～80"],
                ],
            ],

            [
                "item_name" => "光の鍛冶ハンマー",
                "craft_level" => 40,
                "recipe_book" => null,
                "recipe_place" => "真グランゼドーラレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具ハンマー",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "光の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 838, "qty" => 12],
                    ["item_id" => 596, "qty" => 80],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 20],
                ],
                "slot_grid_json" => [
                    ["120～126", "180～186"],
                    ["236～245", "140～149"],
                    ["160～170", "-"],
                ],
            ],
            [
                "item_name" => "光の木工刀",
                "craft_level" => 40,
                "recipe_book" => null,
                "recipe_place" => "真グランゼドーラレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具木工刀",
                "slot_grid_cols" => 1,
                "group_kind" => "craft_tool_set",
                "group_name" => "光の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 838, "qty" => 12],
                    ["item_id" => 597, "qty" => 80],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 20],
                ],
                "slot_grid_json" => [
                    ["249～261"],
                    ["287～293"],
                    ["224～232"],
                ],
            ],
            [
                "item_name" => "光のさいほう針",
                "craft_level" => 40,
                "recipe_book" => null,
                "recipe_place" => "真グランゼドーラレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具さいほう針",
                "slot_grid_cols" => 1,
                "group_kind" => "craft_tool_set",
                "group_name" => "光の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 838, "qty" => 12],
                    ["item_id" => 653, "qty" => 80],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 20],
                ],
                "slot_grid_json" => [
                    ["460～474"],
                    ["376～382"],
                ],
            ],
            [
                "item_name" => "光のフライパン",
                "craft_level" => 40,
                "recipe_book" => null,
                "recipe_place" => "真グランゼドーラレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具フライパン",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "光の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 838, "qty" => 12],
                    ["item_id" => 594, "qty" => 80],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 20],
                ],
                "slot_grid_json" => [
                    ["92～102", "110～120"],
                    ["134～146", "158～164"],
                    ["158～164", "92～102"],
                    ["92～102", "-"],
                ],
            ],
            [
                "item_name" => "光の錬金ランプ",
                "craft_level" => 40,
                "recipe_book" => null,
                "recipe_place" => "真グランゼドーラレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具錬金ランプ",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "光の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 838, "qty" => 12],
                    ["item_id" => 617, "qty" => 80],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 20],
                ],
                "slot_grid_json" => [
                    ["205～213", "306～318"],
                    ["205～213", "120～126"],
                ],
            ],
            [
                "item_name" => "光の錬金ツボ",
                "craft_level" => 40,
                "recipe_book" => null,
                "recipe_place" => "真グランゼドーラレシピ屋",
                "slot" => "その他",
                "slot_grid_type" => "道具錬金ツボ",
                "slot_grid_cols" => 2,
                "group_kind" => "craft_tool_set",
                "group_name" => "光の職人どうぐ",
                "materials_json" => [
                    ["item_id" => 838, "qty" => 12],
                    ["item_id" => 845, "qty" => 80],
                    ["item_id" => 545, "qty" => 30],
                    ["item_id" => 865, "qty" => 20],
                ],
                "slot_grid_json" => [
                    ["100～110", "140～146"],
                    ["140～146", "196～204"],
                    ["160～168", "100～110"],
                ],
            ],
        ];

        $insertRows = array_map(function ($row) use ($now) {
            return [
                "item_id" => $row["item_name"],
                "item_name" => $row["item_name"],
                "equipment_type_id" => null,
                "job_override_mode" => "inherit",
                "craft_level" => $row["craft_level"],
                "equip_level" => null,
                "recipe_book" => $row["recipe_book"],
                "recipe_place" => $row["recipe_place"],
                "description" => null,
                "slot" => $row["slot"],
                "slot_grid_type" => $row["slot_grid_type"],
                "slot_grid_cols" => $row["slot_grid_cols"],
                "group_kind" => $row["group_kind"],
                "group_id" => Str::uuid()->toString(),
                "group_name" => $row["group_name"],
                "materials_json" => json_encode($row["materials_json"], JSON_UNESCAPED_UNICODE),
                "slot_grid_json" => json_encode($row["slot_grid_json"], JSON_UNESCAPED_UNICODE),
                "source_url" => null,
                "detail_url" => null,
                "effects_json" => json_encode([], JSON_UNESCAPED_UNICODE),
                "created_at" => $now,
                "updated_at" => $now,
            ];
        }, $rows);

        DB::table("equipments")->insert($insertRows);
    }
}